spring.application.name=employee-management
spring.datasource.url=jdbc:postgresql://localhost:5432/Dockerdemo
spring.datasource.username=
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080